// YAOS client build (DESIGN §k.1, integration-notes D2).
//   node esbuild.config.mjs production [--analyze] -> main.js + dist/yaos-client/{main.js,manifest.json,yaos/,yaos.zip}, then smoke checks
//   node esbuild.config.mjs                        -> dev: watch, inline sourcemaps, writes main.js
//
// One bundle, src/host/entry.ts -> CJS main.js (obsidian, electron, @codemirror/*,
// @lezer/* external: Obsidian provides them at runtime), wrapped in one named
// function so the engine is in main.js once and serves both carriers:
//   main thread: Obsidian's CJS wrapper calls it with (require, module, exports);
//   worker:      the host builds the worker's Blob from `__yaosBundle.toString()`
//                (src/host/bundleSource.ts) and calls it with the worker scope as
//                4th argument; src/host/entry.ts then starts only the engine.
import esbuild from "esbuild";
import { zipSync } from "fflate";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL(".", import.meta.url));
const OUT = join(ROOT, "dist", "yaos-client");
const prod = process.argv[2] === "production";
const PLUGIN_ID = "yaos";
/** Must match BUNDLE_FUNCTION_NAME in src/host/bundleSource.ts. */
const BUNDLE_FUNCTION_NAME = "__yaosBundle";

const banner = `/*
YAOS ${prod ? "" : "(dev) "}- generated by esbuild.config.mjs. Source: src/host/entry.ts.
*/
(function ${BUNDLE_FUNCTION_NAME}(require, module, exports, __yaosWorkerScope) {`;
const footer = "})(require, module, exports);";

const mainOptions = {
	absWorkingDir: ROOT,
	banner: { js: banner },
	footer: { js: footer },
	entryPoints: ["src/host/entry.ts"],
	bundle: true,
	external: ["obsidian", "electron", "@codemirror/*", "@lezer/*", ...builtinModules],
	format: "cjs",
	platform: "browser",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	legalComments: "none",
	metafile: prod,
};

if (!prod) {
	const ctx = await esbuild.context({ ...mainOptions, outfile: join(ROOT, "main.js") });
	await ctx.watch();
} else {
	const r = await esbuild.build({ ...mainOptions, write: false, outfile: join(ROOT, "main.js") });
	const out = r.outputFiles[0];
	if (!out) throw new Error("main build produced no output");
	const mainJs = out.text;
	const manifestText = readFileSync(join(ROOT, "manifest.json"), "utf8");
	const manifest = JSON.parse(manifestText);
	if (manifest.id !== PLUGIN_ID) throw new Error(`manifest id ${manifest.id}`);
	const enc = new TextEncoder();
	const mainBytes = enc.encode(mainJs);
	const manifestBytes = enc.encode(manifestText);
	writeFileSync(join(ROOT, "main.js"), mainBytes);
	rmSync(join(OUT, PLUGIN_ID), { recursive: true, force: true });
	mkdirSync(join(OUT, PLUGIN_ID), { recursive: true });
	writeFileSync(join(OUT, "main.js"), mainBytes);
	writeFileSync(join(OUT, "manifest.json"), manifestBytes);
	writeFileSync(join(OUT, PLUGIN_ID, "main.js"), mainBytes);
	writeFileSync(join(OUT, PLUGIN_ID, "manifest.json"), manifestBytes);
	const zipPath = join(OUT, `${PLUGIN_ID}.zip`);
	writeFileSync(zipPath, zipSync({ [PLUGIN_ID]: { "main.js": mainBytes, "manifest.json": manifestBytes } }, { level: 9 }));
	const { smokeCheck } = await import("./scripts/plugin-smoke.mjs");
	await smokeCheck({ mainJs, zipPath, manifest, bundleFunctionName: BUNDLE_FUNCTION_NAME });
	if (process.argv.includes("--analyze")) console.log(await esbuild.analyzeMetafile(r.metafile));
	const kib = (n) => `${(n / 1024).toFixed(1)} KiB`;
	console.log(`build: OK  main.js ${kib(mainBytes.length)}`);
	console.log(`build: ${zipPath}`);
	process.exit(0);
}
