// YAOS client build (DESIGN §k.1).
//   node esbuild.config.mjs production   -> main.js + dist/yaos-client/{main.js,manifest.json,yaos/,yaos.zip}, then smoke checks
//   node esbuild.config.mjs              -> dev: watch, inline sourcemaps, writes main.js (worker rebuilt with it)
//
// Two bundles:
//   worker: src/engine/workerMain.ts -> IIFE string (never written), served to the
//           host as `virtual:yaos-engine-worker` and started from a Blob URL;
//   main:   src/host/plugin.ts -> CJS main.js (obsidian, electron, @codemirror/*,
//           @lezer/* external: Obsidian provides them at runtime).
import esbuild from "esbuild";
import { zipSync } from "fflate";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL(".", import.meta.url));
const OUT = join(ROOT, "dist", "yaos-client");
const prod = process.argv[2] === "production";
const PLUGIN_ID = "yaos";

const banner = `/*
YAOS ${prod ? "" : "(dev) "}- generated by esbuild.config.mjs. Source: src/host/plugin.ts (main), src/engine/workerMain.ts (worker).
*/`;

async function buildWorker() {
	const r = await esbuild.build({
		absWorkingDir: ROOT,
		entryPoints: ["src/engine/workerMain.ts"],
		bundle: true,
		format: "iife",
		platform: "browser",
		target: "es2018",
		minify: prod,
		sourcemap: prod ? false : "inline",
		write: false,
		metafile: true,
		logLevel: "warning",
		legalComments: "none",
	});
	const out = r.outputFiles[0];
	if (!out) throw new Error("worker build produced no output");
	return { source: out.text, inputs: Object.keys(r.metafile.inputs).map((p) => resolve(ROOT, p)) };
}

let lastWorker = null;

/** Resolves `virtual:yaos-engine-worker` to the freshly built worker IIFE (watch files = worker inputs). */
const workerPlugin = {
	name: "yaos-engine-worker",
	setup(build) {
		build.onResolve({ filter: /^virtual:yaos-engine-worker$/ }, (args) => ({ path: args.path, namespace: "yaos-worker" }));
		build.onLoad({ filter: /.*/, namespace: "yaos-worker" }, async () => {
			const w = await buildWorker();
			lastWorker = w.source;
			return { contents: `export default ${JSON.stringify(w.source)};`, loader: "js", watchFiles: w.inputs };
		});
	},
};

const mainOptions = {
	absWorkingDir: ROOT,
	banner: { js: banner },
	entryPoints: ["src/host/plugin.ts"],
	bundle: true,
	external: ["obsidian", "electron", "@codemirror/*", "@lezer/*", ...builtinModules],
	format: "cjs",
	platform: "browser",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	legalComments: "none",
	plugins: [workerPlugin],
};

if (!prod) {
	const ctx = await esbuild.context({ ...mainOptions, outfile: join(ROOT, "main.js") });
	await ctx.watch();
} else {
	const r = await esbuild.build({ ...mainOptions, write: false, outfile: join(ROOT, "main.js") });
	const out = r.outputFiles[0];
	if (!out || lastWorker === null) throw new Error("main build produced no output");
	const mainJs = out.text;
	const manifestText = readFileSync(join(ROOT, "manifest.json"), "utf8");
	const manifest = JSON.parse(manifestText);
	if (manifest.id !== PLUGIN_ID) throw new Error(`manifest id ${manifest.id}`);
	const enc = new TextEncoder();
	const mainBytes = enc.encode(mainJs);
	const manifestBytes = enc.encode(manifestText);
	writeFileSync(join(ROOT, "main.js"), mainBytes);
	rmSync(join(OUT, PLUGIN_ID), { recursive: true, force: true });
	mkdirSync(join(OUT, PLUGIN_ID), { recursive: true });
	writeFileSync(join(OUT, "main.js"), mainBytes);
	writeFileSync(join(OUT, "manifest.json"), manifestBytes);
	writeFileSync(join(OUT, PLUGIN_ID, "main.js"), mainBytes);
	writeFileSync(join(OUT, PLUGIN_ID, "manifest.json"), manifestBytes);
	const zipPath = join(OUT, `${PLUGIN_ID}.zip`);
	writeFileSync(zipPath, zipSync({ [PLUGIN_ID]: { "main.js": mainBytes, "manifest.json": manifestBytes } }, { level: 9 }));
	const { smokeCheck } = await import("./scripts/plugin-smoke.mjs");
	await smokeCheck({ mainJs, workerSrc: lastWorker, zipPath, manifest });
	const kib = (n) => `${(n / 1024).toFixed(1)} KiB`;
	console.log(`build: OK  main.js ${kib(mainBytes.length)} (worker ${kib(lastWorker.length)})`);
	console.log(`build: ${zipPath}`);
	process.exit(0);
}
