#!/usr/bin/env python3
"""Write-budget model (PHASE3-WRITE-BUDGET-SPIKE §3 W4): SQLite rows written/day vs the Workers Free 100k limit.

    python3 scripts/relay2/costmodel.py --wb [--measured <raw dir>] [--set name=value]... [--format md|json] [--list]
    python3 scripts/relay2/wb/wbmodel.py   (same flags)

Inputs are named parameters. Each has a default with a provenance tag ("assumed:…", "target:…", "generated:…",
"code:…", "doc:…") and, with --measured <raw dir>, is replaced by the number a W4 scenario JSON reports
("measured:<file>:<field>"). Every output row lists which inputs were measured and which were assumed, and the
table marks a row "measured" only when all of its rows-inputs were measured.

Raw files are found by their "scenario" field (C4W, L5R, I1, I2, I3, I4, A1, XCRASH, R1); for C4W a file whose
relay flag is off is the base comparator. Rows from the relay in-memory fallback counter (rowsSource
"relay-diagnostics", exact=false) are NOT used as measured inputs: they only count relay appends.

Standard library only.
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import os
import sys

# name: (default, provenance, description)
WB_PARAMS: dict[str, tuple[float, str, str]] = {
    "free_rows_written_per_day": (100_000, "doc:developers.cloudflare.com/durable-objects/platform/pricing/",
                                  "SQLite rows written/day (indexes, deletes and setAlarm count)"),
    # ---- per-unit costs (replace with W4 measurements) ----
    "rows_per_typing_s": (9.0, "target:spike §2 (≤ 9)", "rows per second of steady typing at 5 keys/s (C4W steady)"),
    "rows_per_typing_s_burst": (9.0, "target:spike §2", "rows per typing-second with burst/pause typing (C4W burst)"),
    "idle_rows_per_hour": (0.0, "assumed", "rows/hour with sockets open and no edits (C4W idle window)"),
    "rows_per_created_note": (5.0, "target:spike §2 (≤ 5)", "marginal rows per note in a bulk create (I1 fit)"),
    "rows_per_attachment": (3.0, "assumed", "marginal rows per attachment in a bulk create (I1 fit)"),
    "rows_per_batch": (5.0, "target:spike §2 (~5 per batch)", "fixed rows per bulk-create request (I1 fit intercept)"),
    "rows_per_extra_chunk": (1.0, "assumed:one row per extra 1.75 MB snapshot chunk", "rows per extra snapshot chunk"),
    "second_device_rows_per_note": (0.0, "assumed:D4 identical → skip", "rows per note on a second device's first open (I2)"),
    "rows_per_autosave": (3.0, "assumed", "rows per autosave rewrite of a 50 KB file (A1, product diff)"),
    # ---- day shapes (assumed) ----
    "typical_editing_hours": (2.0, "assumed", "typical day: hours of editing (all devices)"),
    "typical_typing_duty": (0.25, "assumed", "typical day: fraction of editing time typing"),
    "typical_burst_fraction": (0.5, "assumed", "typical day: share of typing-seconds in burst/pause pattern"),
    "typical_new_notes": (20, "assumed", "typical day: notes created (each its own batch of one)"),
    "typical_new_attachments": (5, "assumed", "typical day: attachments added (each its own batch)"),
    "typical_hours_open": (10, "assumed", "typical day: hours with Obsidian open (idle rows)"),
    "heavy_editing_hours": (8.0, "assumed", "heavy writer: hours of editing"),
    "heavy_typing_duty": (0.5, "assumed", "heavy writer: fraction of editing time typing"),
    "heavy_new_notes": (100, "assumed", "heavy writer: notes created (batches of one)"),
    "heavy_new_attachments": (40, "assumed", "heavy writer: attachments added"),
    "heavy_folder_drops": (1, "assumed", "heavy writer: folder drops of 200 notes + 50 images"),
    "autosave_hours": (8.0, "assumed", "autosave plugin day: hours a drawing stays open (5 s autosave)"),
    "autosave_interval_s": (5.0, "assumed:A1 shape", "autosave interval"),
    # ---- first-open corpora (generated by wb/corpus.ts, seed wb1; batches at 500 files / 4 MiB, attachment
    #      bytes travel as blobs so only metadata counts) ----
    "fo2k_notes": (2000, "generated:corpus.ts 2k", ""), "fo2k_attachments": (100, "generated:corpus.ts 2k", ""),
    "fo2k_chunks": (2004, "generated:corpus.ts 2k", "snapshot chunks"), "fo2k_batches": (7, "generated:corpus.ts 2k", ""),
    "fo10k_notes": (10000, "generated:corpus.ts 10k", ""), "fo10k_attachments": (500, "generated:corpus.ts 10k", ""),
    "fo10k_chunks": (10020, "generated:corpus.ts 10k", ""), "fo10k_batches": (32, "generated:corpus.ts 10k", ""),
    "fo25k_notes": (25000, "generated:corpus.ts 25k", ""), "fo25k_attachments": (1250, "generated:corpus.ts 25k", ""),
    "fo25k_chunks": (25050, "generated:corpus.ts 25k", ""), "fo25k_batches": (83, "generated:corpus.ts 25k", ""),
    "drop_notes": (200, "generated:corpus.ts drop", ""), "drop_attachments": (50, "generated:corpus.ts drop", ""),
    "drop_batches": (1, "generated:corpus.ts drop", ""),
}


# ------------------------------------------------------------------------------------------- measured extraction
def _g(o, *path):
    for p in path:
        if isinstance(o, dict) and p in o:
            o = o[p]
        else:
            return None
    return o


def _exact(rows) -> bool:
    return isinstance(rows, dict) and rows.get("exact") is True and rows.get("rowsWritten") is not None


def load_runs(raw_dir: str) -> list[tuple[str, dict]]:
    out = []
    for f in sorted(glob.glob(os.path.join(raw_dir, "*.json"))):
        name = os.path.basename(f)
        if name.endswith((".tail.json", ".gql.json")) or name.startswith("convergence-suite"):
            continue
        try:
            d = json.load(open(f, encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        if isinstance(d, dict) and d.get("scenario"):
            out.append((name, d))
    return out


def by_scenario(runs, scenario: str, base: bool | None = False):
    """Runs of `scenario`; base=False → relay (flag on or unknown), True → relay off, None → any."""
    xs = []
    for name, d in runs:
        if d.get("scenario") != scenario or d.get("error"):
            continue
        is_base = d.get("relay") is False or d.get("protocolAdapter") == "base"
        if base is None or is_base == base:
            xs.append((name, d))
    return xs


def extract_measured(raw_dir: str) -> tuple[dict[str, float], dict[str, str], list[str]]:
    """→ (values, provenance, notes). Only exact counter readings are used."""
    runs = load_runs(raw_dir)
    vals: dict[str, float] = {}
    prov: dict[str, str] = {}
    notes: list[str] = []

    def put(param, value, src):
        if value is None or (isinstance(value, float) and math.isnan(value)):
            return
        vals[param] = float(value)
        prov[param] = f"measured:{src}"

    for name, d in by_scenario(runs, "C4W"):
        for part in d.get("parts") or []:
            rows = part.get("rows")
            if not _exact(rows):
                notes.append(f"{name} {part.get('part')}: rows source {_g(rows, 'source')} not exact — ignored")
                continue
            if part.get("part") == "steady":
                put("rows_per_typing_s", part.get("rowsPerTypingSecond"), f"{name}:steady.rowsPerTypingSecond")
            elif part.get("part") == "burst":
                put("rows_per_typing_s_burst", part.get("rowsPerTypingSecond"), f"{name}:burst.rowsPerTypingSecond")
            elif part.get("part") == "idle":
                ms = rows.get("ms") or 0
                if ms > 0:
                    put("idle_rows_per_hour", rows["rowsWritten"] * 3_600_000 / ms, f"{name}:idle.rows")
    # I1/I2 are HTTP create paths: protocolAdapter is just the unused ws default ("base"), so take any run.
    for name, d in by_scenario(runs, "I1", base=None):
        if d.get("rowsExact") is not True:
            notes.append(f"{name}: I1 rows source {d.get('rowsSource')} not exact — ignored")
            continue
        fit = d.get("fit") or {}
        put("rows_per_created_note", fit.get("rowsPerNote"), f"{name}:fit.rowsPerNote")
        put("rows_per_attachment", fit.get("rowsPerAttachment"), f"{name}:fit.rowsPerAttachment")
        put("rows_per_batch", fit.get("rowsPerBatch"), f"{name}:fit.rowsPerBatch")
        if not fit:
            notes.append(f"{name}: no batch fit (too few batches); using totals only")
        if d.get("adapter") != "bulk":
            notes.append(f"{name}: create adapter {d.get('adapter')} (not W2 bulk) — per-note rows describe that path")
    for name, d in by_scenario(runs, "I2", base=None):
        for mode in ("bulk", "catalog"):
            part = d.get(mode) or {}
            rows = part.get("rows") if mode == "catalog" else {"rowsWritten": part.get("totalRowsWritten"), "exact": part.get("rowsExact")}
            n = _g(d, "corpus", "stats", "notes")
            if _exact(rows) and n:
                put("second_device_rows_per_note", rows["rowsWritten"] / n, f"{name}:{mode}.rows/notes")
                break
    for name, d in by_scenario(runs, "A1"):
        if d.get("mode") not in (None, "diff"):
            continue
        if _exact(d.get("rows")):
            put("rows_per_autosave", d.get("rowsPerWrite"), f"{name}:rowsPerWrite")
        else:
            notes.append(f"{name}: A1 rows not exact — ignored")
    return vals, prov, notes


# ------------------------------------------------------------------------------------------- model
def _row(label, parts: dict[str, float], uses: list[str], prov: dict[str, str], p, notes=""):
    rows = sum(parts.values())
    measured = [u for u in uses if prov[u].startswith("measured")]
    assumed = [u for u in uses if not prov[u].startswith("measured")]
    limit = p["free_rows_written_per_day"]
    return {"shape": label, "rowsPerDay": rows, "pctFree": 100 * rows / limit, "daysToComplete": math.ceil(rows / limit) if rows > limit else 1,
            "breakdown": parts, "measuredInputs": measured, "assumedInputs": assumed,
            "label": "measured" if not assumed else ("partly measured" if measured else "assumed"), "notes": notes}


def first_open(p, prov, key, label):
    n, a, c, b = p[f"{key}_notes"], p[f"{key}_attachments"], p[f"{key}_chunks"], p[f"{key}_batches"]
    parts = {"notes": n * p["rows_per_created_note"], "attachments": a * p["rows_per_attachment"],
             "batches": b * p["rows_per_batch"], "extraChunks": max(0, c - n) * p["rows_per_extra_chunk"]}
    return _row(label, parts, ["rows_per_created_note", "rows_per_attachment", "rows_per_batch", "rows_per_extra_chunk"], prov, p,
                f"{n:,.0f} notes + {a:,.0f} attachments in {b:,.0f} requests")


def model(p: dict[str, float], prov: dict[str, str]) -> list[dict]:
    rows = []
    ts = p["typical_editing_hours"] * 3600 * p["typical_typing_duty"]
    bf = p["typical_burst_fraction"]
    rows.append(_row("typical day", {
        "typing": ts * ((1 - bf) * p["rows_per_typing_s"] + bf * p["rows_per_typing_s_burst"]),
        "creates": p["typical_new_notes"] * (p["rows_per_created_note"] + p["rows_per_batch"]),
        "attachments": p["typical_new_attachments"] * (p["rows_per_attachment"] + p["rows_per_batch"]),
        "idle": p["typical_hours_open"] * p["idle_rows_per_hour"],
    }, ["rows_per_typing_s", "rows_per_typing_s_burst", "rows_per_created_note", "rows_per_attachment", "rows_per_batch", "idle_rows_per_hour"],
        prov, p, f"{ts / 3600:.2f} typing-hours, {p['typical_new_notes']:.0f} new notes"))
    hs = p["heavy_editing_hours"] * 3600 * p["heavy_typing_duty"]
    rows.append(_row("heavy writer", {
        "typing": hs * 0.5 * (p["rows_per_typing_s"] + p["rows_per_typing_s_burst"]),
        "creates": p["heavy_new_notes"] * (p["rows_per_created_note"] + p["rows_per_batch"]),
        "attachments": p["heavy_new_attachments"] * (p["rows_per_attachment"] + p["rows_per_batch"]),
        "folderDrops": p["heavy_folder_drops"] * (p["drop_notes"] * p["rows_per_created_note"] + p["drop_attachments"] * p["rows_per_attachment"]
                                                  + p["drop_batches"] * p["rows_per_batch"]),
        "idle": 16 * p["idle_rows_per_hour"],
    }, ["rows_per_typing_s", "rows_per_typing_s_burst", "rows_per_created_note", "rows_per_attachment", "rows_per_batch", "idle_rows_per_hour"],
        prov, p, f"{hs / 3600:.1f} typing-hours, {p['heavy_new_notes']:.0f} notes, {p['heavy_folder_drops']:.0f} folder drop(s)"))
    saves = p["autosave_hours"] * 3600 / p["autosave_interval_s"]
    rows.append(_row("autosave plugin (50 KB / 5 s)", {"autosaves": saves * p["rows_per_autosave"]}, ["rows_per_autosave"], prov, p,
                     f"{saves:,.0f} rewrites over {p['autosave_hours']:.0f} h, on top of the user's own day"))
    rows.append(first_open(p, prov, "fo2k", "first open 2k notes"))
    rows.append(first_open(p, prov, "fo10k", "first open 10k notes"))
    rows.append(first_open(p, prov, "fo25k", "first open 25k notes"))
    rows.append(_row("second device first open 25k", {"notes": p["fo25k_notes"] * p["second_device_rows_per_note"]},
                     ["second_device_rows_per_note"], prov, p, "identical content → skip (D4)"))
    return rows


def headroom(p, prov):
    """Typing-hours per day before 100k, and notes creatable per day in full batches."""
    per_h = 3600 * p["rows_per_typing_s"]
    per_note_bulk = p["rows_per_created_note"] + p["rows_per_batch"] / 500
    return {"typingHoursTo100k": p["free_rows_written_per_day"] / per_h if per_h else math.inf,
            "notesPerDayInFullBatches": p["free_rows_written_per_day"] / per_note_bulk if per_note_bulk else math.inf,
            "singleCreatesPerDay": p["free_rows_written_per_day"] / (p["rows_per_created_note"] + p["rows_per_batch"]),
            "labels": {k: prov[k] for k in ("rows_per_typing_s", "rows_per_created_note", "rows_per_batch")}}


def render(rows, p, prov, hr, notes) -> str:
    out = ["| Day shape | Rows written/day | % of 100k | Days to finish | Basis | Assumed inputs | Notes |", "|---|---:|---:|---:|---|---|---|"]
    for r in rows:
        out.append(f"| {r['shape']} | {r['rowsPerDay']:,.0f} | {r['pctFree']:.0f}% | {r['daysToComplete']} | {r['label']} | "
                   f"{', '.join(r['assumedInputs']) or '–'} | {r['notes']} |")
    out += ["", "| Headroom | Value | Basis |", "|---|---:|---|",
            f"| typing-hours/day to 100k rows | {hr['typingHoursTo100k']:.1f} | {hr['labels']['rows_per_typing_s']} |",
            f"| notes/day in full 500-file batches | {hr['notesPerDayInFullBatches']:,.0f} | {hr['labels']['rows_per_created_note']}; {hr['labels']['rows_per_batch']} |",
            f"| single-note creates/day | {hr['singleCreatesPerDay']:,.0f} | as above |",
            "", "Inputs:", "", "| Parameter | Value | Provenance |", "|---|---:|---|"]
    for k in ("rows_per_typing_s", "rows_per_typing_s_burst", "idle_rows_per_hour", "rows_per_created_note", "rows_per_attachment",
              "rows_per_batch", "rows_per_extra_chunk", "second_device_rows_per_note", "rows_per_autosave"):
        out.append(f"| {k} | {p[k]:g} | {prov[k]} |")
    if notes:
        out += ["", "Extraction notes:", ""] + [f"- {n}" for n in notes]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--measured", help="raw dir of W4 scenario JSONs")
    ap.add_argument("--set", action="append", default=[], metavar="NAME=VALUE")
    ap.add_argument("--format", choices=["md", "json"], default="md")
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args(argv)
    if a.list:
        for k, (v, pv, desc) in WB_PARAMS.items():
            print(f"{k:32} {v!s:>10}  {pv:44} {desc}")
        return 0
    p = {k: float(v[0]) for k, v in WB_PARAMS.items()}
    prov = {k: v[1] for k, v in WB_PARAMS.items()}
    notes: list[str] = []
    if a.measured:
        vals, mprov, notes = extract_measured(a.measured)
        p.update(vals)
        prov.update(mprov)
    for item in a.set:
        k, _, v = item.partition("=")
        if k not in p:
            print(f"unknown parameter {k}", file=sys.stderr)
            return 2
        p[k] = float(v)
        prov[k] = "override:--set"
    rows = model(p, prov)
    hr = headroom(p, prov)
    if a.format == "json":
        print(json.dumps({"params": p, "provenance": prov, "rows": rows, "headroom": hr, "notes": notes}, indent=2))
    else:
        print(render(rows, p, prov, hr, notes))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
