import {
	PROTOCOL_VERSION,
	SCHEMA_VERSION,
	SNAPSHOT_FORMAT_VERSION,
	STORAGE_FORMAT_VERSION,
} from "./shared/productVersions";

export const SERVER_VERSION = "1.0.0";
export const SERVER_SCHEMA_VERSION = SCHEMA_VERSION;
export const SERVER_STORAGE_FORMAT_VERSION = STORAGE_FORMAT_VERSION;
export const SERVER_PROTOCOL_VERSION = PROTOCOL_VERSION;
export const SERVER_SNAPSHOT_FORMAT_VERSION = SNAPSHOT_FORMAT_VERSION;
