#!/usr/bin/env node
// Builds the throwaway YAOS day-1 spike plugin (OR-1 worker/IDB, OR-2 setViewData,
// E2EE WebCrypto-in-worker probes for docs/client-remake/e2ee-design.md).
//   pass 1: src/host/spike/spikeWorker.ts -> IIFE string (browser, es2018, minified, not written)
//   pass 2: src/host/spike/main.ts -> CJS main.js with the worker source injected via
//           define __YAOS_SPIKE_WORKER_SRC__ (no virtual module)
// Writes dist/yaos-client/spike/{main.js,manifest.json}, a ready-to-copy
// dist/yaos-client/spike/yaos-spike/ folder, and yaos-spike.zip (top-level yaos-spike/).
// Then smoke-checks the bundle in node: main.js loads as CJS against a stub
// "obsidian" module and registers its commands; the worker IIFE boots and answers
// ping/probe/crypto inside a node:vm context.
// Usage: node scripts/build-spike.mjs [--out <path/to/yaos-spike.zip>]
//   --out copies the checked zip there after every smoke check passed.
import esbuild from "esbuild";
import { zipSync, unzipSync, strFromU8 } from "fflate";
import { copyFileSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { webcrypto } from "node:crypto";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(ROOT, "dist", "yaos-client", "spike");
const PLUGIN_ID = "yaos-spike";
const outIdx = process.argv.indexOf("--out");
const COPY_TO = outIdx > 0 ? process.argv[outIdx + 1] : undefined;
if (outIdx > 0 && (!COPY_TO || !COPY_TO.endsWith(".zip"))) {
	console.error("build-spike: --out needs a path ending in .zip");
	process.exit(1);
}

const manifest = {
	id: PLUGIN_ID,
	name: "YAOS Spike",
	version: "0.0.2",
	minAppVersion: "1.5.0",
	description:
		"Throwaway YAOS day-1 spike: probes Blob-URL worker + IndexedDB (OR-1), MarkdownView reload / setViewData interception (OR-2) and WebCrypto in the worker for E2EE (AES-GCM, HKDF, HMAC, non-extractable keys in IndexedDB, throughput). Use in a test vault only.",
	author: "YAOS",
	isDesktopOnly: false,
};

const buildId = new Date().toISOString();

function fail(msg) {
	console.error(`build-spike: FAIL ${msg}`);
	process.exit(1);
}

// ---- pass 1: worker IIFE ---------------------------------------------------
const workerBuild = await esbuild.build({
	absWorkingDir: ROOT,
	entryPoints: ["src/host/spike/spikeWorker.ts"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2018",
	minify: true,
	write: false,
	logLevel: "warning",
	legalComments: "none",
});
const workerSrc = workerBuild.outputFiles[0].text;

// ---- pass 2: plugin main (CJS) ----------------------------------------------
const mainBuild = await esbuild.build({
	absWorkingDir: ROOT,
	entryPoints: ["src/host/spike/main.ts"],
	bundle: true,
	format: "cjs",
	platform: "browser",
	target: "es2018",
	minify: true,
	write: false,
	logLevel: "warning",
	legalComments: "none",
	external: ["obsidian", "electron", "@codemirror/*", "@lezer/*"],
	define: {
		__YAOS_SPIKE_WORKER_SRC__: JSON.stringify(workerSrc),
		__YAOS_SPIKE_BUILD__: JSON.stringify(buildId),
	},
	banner: { js: `/* YAOS spike ${manifest.version} (${buildId}) - throwaway diagnostic plugin, generated by scripts/build-spike.mjs */` },
});
const mainJs = mainBuild.outputFiles[0].text;

// ---- write outputs ----------------------------------------------------------
const enc = new TextEncoder();
const mainBytes = enc.encode(mainJs);
const manifestBytes = enc.encode(JSON.stringify(manifest, null, "\t") + "\n");

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, PLUGIN_ID), { recursive: true });
writeFileSync(join(OUT, "main.js"), mainBytes);
writeFileSync(join(OUT, "manifest.json"), manifestBytes);
writeFileSync(join(OUT, PLUGIN_ID, "main.js"), mainBytes);
writeFileSync(join(OUT, PLUGIN_ID, "manifest.json"), manifestBytes);
const zip = zipSync({ [PLUGIN_ID]: { "main.js": mainBytes, "manifest.json": manifestBytes } }, { level: 9 });
const zipPath = join(OUT, `${PLUGIN_ID}.zip`);
writeFileSync(zipPath, zip);

// ---- smoke 1: zip layout ----------------------------------------------------
{
	const entries = unzipSync(readFileSync(zipPath));
	const names = Object.keys(entries).sort();
	const want = [`${PLUGIN_ID}/main.js`, `${PLUGIN_ID}/manifest.json`];
	if (!want.every((n) => names.includes(n))) fail(`zip entries ${JSON.stringify(names)}`);
	if (strFromU8(entries[`${PLUGIN_ID}/main.js`]) !== mainJs) fail("zip main.js differs");
	if (JSON.parse(strFromU8(entries[`${PLUGIN_ID}/manifest.json`])).id !== PLUGIN_ID) fail("zip manifest id");
}

// ---- smoke 2: forbidden content -----------------------------------------------
if (mainJs.includes("WebAssembly") || workerSrc.includes("WebAssembly")) fail("bundle mentions WebAssembly");
if (!mainJs.includes("yaos-spike-probe")) fail("main.js missing the view probe");

// ---- smoke 3: main.js loads as CJS against a stub "obsidian" ----------------
{
	class Component {}
	class Plugin extends Component {
		constructor(app, mf) {
			super();
			this.app = app;
			this.manifest = mf;
			this.commands = [];
			this.ribbons = [];
		}
		addRibbonIcon(icon, title, cb) {
			this.ribbons.push({ icon, title, cb });
			return {};
		}
		addCommand(cmd) {
			this.commands.push(cmd);
			return cmd;
		}
		register() {}
		registerEvent() {}
	}
	class Modal {
		constructor(app) {
			this.app = app;
		}
		open() {}
		close() {}
	}
	class Notice {
		constructor(message) {
			this.message = message;
		}
		setMessage(m) {
			this.message = m;
			return this;
		}
		hide() {}
	}
	class View {}
	class TextFileView extends View {}
	class MarkdownView extends TextFileView {}
	class TAbstractFile {}
	class TFile extends TAbstractFile {}
	class TFolder extends TAbstractFile {}
	const obsidianStub = {
		Plugin,
		Component,
		Modal,
		Notice,
		View,
		TextFileView,
		MarkdownView,
		TAbstractFile,
		TFile,
		TFolder,
		Platform: { isDesktop: true, isMobile: false, isDesktopApp: true, isMobileApp: false, isIosApp: false, isAndroidApp: false, isPhone: false, isTablet: false, isMacOS: true, isWin: false, isLinux: false, isSafari: false },
		apiVersion: "1.5.0-stub",
		normalizePath: (p) => p.replace(/\/+/g, "/").replace(/^\/|\/$/g, ""),
	};
	const requested = [];
	const fakeRequire = (id) => {
		requested.push(id);
		if (id === "obsidian") return obsidianStub;
		throw new Error(`unexpected require(${JSON.stringify(id)})`);
	};
	const mod = { exports: {} };
	// Obsidian evaluates plugin code as a CJS function body with module/exports/require.
	const fn = vm.runInThisContext(`(function (module, exports, require) {${mainJs}\n})`, { filename: "yaos-spike/main.js" });
	fn(mod, mod.exports, fakeRequire);
	const Ctor = mod.exports.default;
	if (typeof Ctor !== "function") fail(`module.exports.default is ${typeof Ctor}`);
	if (requested.some((id) => id !== "obsidian")) fail(`unexpected requires ${requested.join(",")}`);
	const plugin = new Ctor({ vault: {}, workspace: {} }, manifest);
	if (!(plugin instanceof Plugin)) fail("default export does not extend Plugin");
	plugin.onload();
	const ids = plugin.commands.map((c) => c.id).sort();
	const wantIds = ["run-e2ee", "run-or1", "run-or2", "run-probes", "show-last-report"];
	if (JSON.stringify(ids) !== JSON.stringify(wantIds)) fail(`commands ${JSON.stringify(ids)}`);
	if (plugin.ribbons.length !== 1) fail("expected one ribbon icon");
}

// ---- smoke 4: worker IIFE boots and answers inside node:vm ------------------
{
	const posted = [];
	const listeners = new Map();
	let notify = () => {};
	const ctx = vm.createContext({
		postMessage: (m) => {
			posted.push(m);
			notify();
		},
		addEventListener: (type, l) => {
			const arr = listeners.get(type) ?? [];
			arr.push(l);
			listeners.set(type, arr);
		},
		setTimeout,
		clearTimeout,
		console,
		performance,
		TextEncoder,
		crypto: webcrypto,
	});
	vm.runInContext(workerSrc, ctx, { filename: "spike-worker.js" });
	const send = (data) => {
		for (const l of listeners.get("message") ?? []) l({ data });
	};
	const waitFor = (pred, ms) =>
		new Promise((resolve, reject) => {
			const t = setTimeout(() => reject(new Error(`worker smoke timeout; posted=${JSON.stringify(posted.map((m) => m.type))}`)), ms);
			const check = () => {
				const hit = posted.find(pred);
				if (hit) {
					clearTimeout(t);
					resolve(hit);
				}
			};
			notify = check;
			check();
		});
	try {
		await waitFor((m) => m.type === "boot", 1000);
		send({ type: "ping", id: 1, t: 0 });
		await waitFor((m) => m.type === "pong" && m.id === 1, 1000);
		send({ type: "probe", id: 2, idbTimeoutMs: 200 });
		const pr = await waitFor((m) => m.type === "probeResult" && m.id === 2, 5000);
		const r = pr.report;
		if (r.typeofIndexedDB !== "undefined" || r.idb.ok !== false) fail(`vm worker idb ${JSON.stringify(r.idb)}`);
		const want = webcrypto.subtle ? Buffer.from(await webcrypto.subtle.digest("SHA-256", new TextEncoder().encode("yaos"))).toString("hex") : null;
		if (r.cryptoSubtle.digest.value !== want) fail(`vm worker digest ${JSON.stringify(r.cryptoSubtle)}`);
		// E2EE crypto probe: every WebCrypto check passes in the vm worker; IDB is absent there, so idbKey is skipped.
		send({ type: "crypto", id: 3, opts: { sizes: [1024, 65536], benchMs: 5, benchMaxIters: 10 } });
		const cr = (await waitFor((m) => m.type === "cryptoResult" && m.id === 3, 15000)).report;
		for (const step of ["random", "importNonExtractable", "hkdf", "hmac", "aesGcm"]) {
			if (cr[step].ok !== true) fail(`vm worker crypto ${step} ${JSON.stringify(cr[step])}`);
		}
		if (cr.hkdf.value.rfc5869A1 !== true || cr.hmac.value.rfc4231Tc2 !== true || cr.aesGcm.value.gcmTc16Encrypt !== true) fail("vm worker crypto KAT");
		if (cr.aesGcm.value.tamperTag !== "OperationError" || cr.aesGcm.value.wrongAad !== "OperationError") fail(`vm worker crypto tamper ${JSON.stringify(cr.aesGcm.value)}`);
		if (cr.idbKey.skipped !== true) fail(`vm worker crypto idbKey ${JSON.stringify(cr.idbKey)}`);
		if (!cr.bench.ok || cr.bench.rows.length !== 2) fail(`vm worker crypto bench ${JSON.stringify(cr.bench)}`);
	} catch (e) {
		fail(e instanceof Error ? e.message : String(e));
	}
}

const kib = (n) => `${(n / 1024).toFixed(1)} KiB`;
console.log(`build-spike: OK  main.js ${kib(mainBytes.length)} (worker ${kib(workerSrc.length)})  zip ${kib(zip.length)}`);
console.log(`build-spike: ${zipPath}`);
console.log(`build-spike: ${join(OUT, PLUGIN_ID)}/ (copy this folder into <vault>/.obsidian/plugins/)`);
if (COPY_TO) {
	copyFileSync(zipPath, resolve(COPY_TO));
	console.log(`build-spike: copied zip to ${resolve(COPY_TO)}`);
}
