export const MAX_FRONTMATTER_SEMANTIC_FIELDS = 256;
export const MAX_FRONTMATTER_SET_TOKENS = 4096;
export const MAX_FRONTMATTER_ORDERED_VALUES = 256;
export const MAX_FRONTMATTER_FIELD_BYTES = 256;
export const MAX_FRONTMATTER_TOKEN_BYTES = 256;
export const MAX_FRONTMATTER_SCALAR_STRING_BYTES = 16 * 1024;
export const MAX_FRONTMATTER_NORMALIZED_VALUE_BYTES = MAX_FRONTMATTER_SCALAR_STRING_BYTES + 32;
export const MAX_FRONTMATTER_SEMANTIC_SERIALIZED_BYTES = 256 * 1024;
