// Build the released `yaos` CLI: one bundled ESM file, run by plain `node`.
//
// WHY A BUNDLE AND NOT A TSC EMIT. The daemon's engine is `src/**` — the same
// TypeScript the Obsidian plugin ships — imported by repository-relative path
// (`../../../src/sync/vaultSync.ts`). Those imports are meaningful inside this
// repository and meaningless inside an installed package, and the engine also
// imports the bare specifier `obsidian`, whose npm package ships type
// declarations and no JavaScript at all. A tsc emit would preserve both
// problems; bundling erases both. `obsidian` is resolved HERE, at build time,
// to the daemon's own runtime shim, so the shipped artifact has no module
// alias, no loader hook and no TypeScript on its runtime path.
//
// This mirrors the plugin build at the repository root (esbuild.config.mjs):
// same bundler, same "externalise what the host really provides" rule. Only
// the host differs — Node, not Electron — so the external list differs.

import { builtinModules } from "node:module";
import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import esbuild from "esbuild";

const PACKAGE_ROOT = fileURLToPath(new URL(".", import.meta.url));
const REPO_ROOT = path.resolve(PACKAGE_ROOT, "../..");

/**
 * Packages the built artifact loads from `node_modules` at runtime. This list
 * and `package.json`'s `dependencies` are the same claim written twice, and
 * `verifyDependencies` below fails the build when they disagree.
 *
 *   chokidar — the vault watcher. Its job is to pick the best facility the
 *     host OS offers (fs.watch, fsevents on macOS, polling as a fallback) and
 *     that choice belongs to the installed machine, not to our build machine.
 *     It also reaches for an optional native module on some platforms, which a
 *     bundler cannot carry.
 *
 *   ws — the WebSocket transport. It `require`s the optional native addons
 *     `bufferutil` and `utf-8-validate` inside try/catch. Bundling would turn
 *     those into hard, unresolvable imports and would pin the daemon to
 *     whichever `ws` this repository happened to have at build time, for a
 *     package whose whole point is to track the platform's socket behaviour.
 *
 * EVERYTHING ELSE IS BUNDLED, and `yjs` deliberately so. Two Yjs instances in
 * one process is a documented hazard in this repository: Yjs identifies types
 * with `instanceof` and a second copy makes every check silently false, so
 * documents stop reconciling with no error anywhere. Leaving it external would
 * hand that decision to whatever `node_modules` tree the daemon is installed
 * into, where an ESM copy and a CJS copy of the same version are two copies.
 * Bundling it — together with every consumer of it, `y-partyserver` and
 * `y-protocols` included — makes exactly one instance a property of the
 * artifact rather than a property of the installation.
 */
const RUNTIME_DEPENDENCIES = ["chokidar", "ws"];

const OUT_FILE = "yaos.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

function parseArgs(argv) {
	let outdir = path.join(PACKAGE_ROOT, "dist");
	let metafile = false;
	for (const arg of argv) {
		if (arg.startsWith("--outdir=")) outdir = path.resolve(arg.slice("--outdir=".length));
		else if (arg === "--metafile") metafile = true;
		else throw new Error(`Unknown argument: ${arg}`);
	}
	return { outdir, metafile };
}

/**
 * Fail the build when the artifact's real imports and the package's declared
 * `dependencies` are not the same set.
 *
 * A missing entry ships a CLI that crashes on `node_modules` resolution at the
 * customer's first run; a surplus entry installs weight the artifact never
 * loads. Both are invisible in a green build, so they are checked here against
 * esbuild's own record of what it left external rather than against a comment.
 */
async function verifyDependencies(metafile) {
	const manifest = JSON.parse(await readFile(path.join(PACKAGE_ROOT, "package.json"), "utf8"));
	const declared = manifest.dependencies ?? {};

	const builtins = new Set(builtinModules);
	const imported = new Set();
	for (const output of Object.values(metafile.outputs)) {
		for (const specifier of output.imports ?? []) {
			if (specifier.kind === "require-resolve") continue;
			const name = specifier.path;
			if (name.startsWith("node:") || builtins.has(name)) continue;
			// Bare specifier → the package it belongs to (`ws/lib/x` → `ws`).
			imported.add(name.startsWith("@") ? name.split("/").slice(0, 2).join("/") : name.split("/")[0]);
		}
	}

	const missing = [...imported].filter((name) => !(name in declared)).sort();
	const surplus = Object.keys(declared).filter((name) => !imported.has(name)).sort();
	if (missing.length > 0 || surplus.length > 0) {
		const lines = ["packages/cli/package.json dependencies do not match the built artifact:"];
		for (const name of missing) lines.push(`  imported but not declared: ${name}`);
		for (const name of surplus) lines.push(`  declared but never imported: ${name}`);
		throw new Error(lines.join("\n"));
	}
	return [...imported].sort();
}

const { outdir, metafile: writeMetafile } = parseArgs(process.argv.slice(2));

// Deterministic: the output directory is rebuilt from nothing every time, so a
// renamed or deleted entry point cannot leave a stale file behind that the next
// run appears to succeed with.
await rm(outdir, { recursive: true, force: true });

const result = await esbuild.build({
	absWorkingDir: REPO_ROOT,
	entryPoints: [path.join(PACKAGE_ROOT, "src/index.ts")],
	outfile: path.join(outdir, OUT_FILE),
	banner: { js: banner },
	bundle: true,
	platform: "node",
	format: "esm",
	// Node 24 is the first supported runtime: the client database uses
	// stable built-in node:sqlite and ships no native database addon.
	target: "node24",
	// The runtime alias the dev launcher used to install via JITI_ALIAS,
	// applied at build time instead. After this the string "obsidian" does not
	// appear as an import anywhere in the artifact.
	alias: {
		obsidian: path.join(PACKAGE_ROOT, "src/obsidian-shim.ts"),
		// `src/sync/diskIndex.ts` imports "@shared/concurrency"; the plugin
		// build gets this from tsconfig `paths`, which esbuild only reads for
		// the tsconfig nearest each file. Stated explicitly so the mapping is
		// visible where the bundle is defined.
		"@shared": path.join(REPO_ROOT, "server/src/shared"),
	},
	external: [...RUNTIME_DEPENDENCIES, ...builtinModules],
	define: {
		// Same contract as the plugin build: false → esbuild dead-code
		// eliminates the QA engine control port. A daemon must never carry it.
		"__YAOS_QA_HARNESS_ENABLED__": "false",
	},
	// NOT MINIFIED, unlike the plugin. The plugin's size is a user-visible
	// download; a daemon's is not, and the only diagnostic an operator gets
	// from a crashed service is the stack trace in the journal. Readable frames
	// are worth more here than bytes.
	minify: false,
	// `*.map` is gitignored repository-wide and a sourcemap next to a released
	// binary is a file that goes stale silently. The bundle is readable.
	sourcemap: false,
	treeShaking: true,
	metafile: true,
	logLevel: "info",
});

// Before verification, not after: when the dependency check fails, the record
// of what esbuild actually resolved is exactly what diagnoses it.
if (writeMetafile) {
	await writeFile(path.join(outdir, "metafile.json"), JSON.stringify(result.metafile, null, 2));
}

const runtimeImports = await verifyDependencies(result.metafile);

process.stdout.write(
	`[cli:build] ${path.relative(REPO_ROOT, path.join(outdir, OUT_FILE))}\n` +
	`[cli:build] external at runtime: ${runtimeImports.join(", ") || "(none beyond node builtins)"}\n`,
);
