// Renders a relay wrangler config (scripts/relay-dev/config.sh output) as a cf project: cloudflare.config.ts
// (the Worker) + wrangler.config.ts (build tooling: alias and module rules), for `cf deploy` (scripts/relay-dev/deploy.sh).
//
//   node scripts/relay-dev/cf-config.mjs <wrangler.toml> <project-dir>
//
// The toml is read with the pinned wrangler's own reader (cf-deploy/node_modules), so the cf project matches
// what `wrangler deploy -c <toml>` would upload. cf configs have no [[migrations]]: the folded migration list
// becomes the `exports` lifecycle declaration (one live entry per class), which the upload API reconciles
// against the classes a redeployed worker already has (same classes = same namespaces). deleted_classes become
// `deleted` tombstones: the upload API rejects a provisioned namespace that is neither live nor tombstoned.
// [[r2_buckets]] become `bindings.r2({ name: <bucket_name> })` (cf/config converts that back to the same
// r2_buckets entry); the bucket must already exist on the account, since a binding without a bucket_name is refused
// rather than left for cf to provision.
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

const require = createRequire(import.meta.url);
const { unstable_readConfig } = require("./cf-deploy/node_modules/wrangler");

const [tomlArg, dirArg] = process.argv.slice(2);
if (!tomlArg || !dirArg) {
	console.error("usage: cf-config.mjs <wrangler.toml> <project-dir>");
	process.exit(2);
}
const toml = resolve(tomlArg);
const dir = resolve(dirArg);
const cfg = unstable_readConfig({ config: toml }, { hideWarnings: true });
const rel = (p) => {
	const r = relative(dir, resolve(dirname(toml), p));
	return r.startsWith(".") ? r : `./${r}`;
};
const fail = (msg) => {
	console.error(`cf-config: ${msg}`);
	process.exit(1);
};

if (cfg.kv_namespaces?.length || cfg.d1_databases?.length || cfg.services?.length) {
	fail("only Durable Object, R2 and text bindings are supported (the streams relay config has no KV/D1/services)");
}

// Fold [[migrations]] into the final class set.
const classes = new Map();
const deleted = new Set();
for (const m of cfg.migrations ?? []) {
	for (const c of m.new_sqlite_classes ?? []) { classes.set(c, "sqlite"); deleted.delete(c); }
	for (const c of m.new_classes ?? []) { classes.set(c, "legacy-kv"); deleted.delete(c); }
	for (const c of m.deleted_classes ?? []) { classes.delete(c); deleted.add(c); }
	for (const { from, to } of m.renamed_classes ?? []) {
		if (!classes.has(from)) fail(`renamed class ${from} was never created`);
		classes.set(to, classes.get(from));
		classes.delete(from);
	}
	if (m.transferred_classes?.length) fail("transferred_classes are not supported");
}

const q = JSON.stringify;
const env = [];
for (const [k, v] of Object.entries(cfg.vars ?? {})) {
	if (typeof v !== "string") fail(`var ${k} is not a string`);
	env.push(`\t\t\t${q(k)}: bindings.text(${q(v)}),`);
}
for (const b of cfg.durable_objects?.bindings ?? []) {
	if (b.script_name) fail(`binding ${b.name} points at another worker`);
	if (!classes.has(b.class_name)) fail(`binding ${b.name} uses class ${b.class_name}, which no migration creates`);
	env.push(`\t\t\t${q(b.name)}: bindings.durableObject({ worker: ${q(cfg.name)}, exportName: ${q(b.class_name)} }),`);
}
for (const b of cfg.r2_buckets ?? []) {
	if (typeof b.bucket_name !== "string" || !b.bucket_name) fail(`R2 binding ${b.binding} has no bucket_name`);
	const jurisdiction = b.jurisdiction ? `, jurisdiction: ${q(b.jurisdiction)}` : "";
	env.push(`\t\t\t${q(b.binding)}: bindings.r2({ name: ${q(b.bucket_name)}${jurisdiction} }),`);
}
const exportsLines = [...classes].map(([c, storage]) => `\t\t\t${q(c)}: exports.durableObject({ storage: ${q(storage)} }),`);
for (const c of deleted) exportsLines.push(`\t\t\t${q(c)}: exports.durableObject({ state: "deleted" }),`);
const flags = cfg.compatibility_flags?.length ? `\t\tcompatibilityFlags: ${q(cfg.compatibility_flags)},\n` : "";
const logs = cfg.observability?.logs?.enabled ?? cfg.observability?.enabled;
const observability = logs ? `\t\tobservability: { logs: { enabled: true } },\n` : "";

const cloudflareConfig = `// Generated by scripts/relay-dev/cf-config.mjs from ${relative(dir, toml)}. Do not edit.
import { bindings, defineConfig, exports } from "cf/config";

export default defineConfig({
	worker: {
		name: ${q(cfg.name)},
		compatibilityDate: ${q(cfg.compatibility_date)},
${flags}		entrypoint: ${q(rel(cfg.main))},
		workersDev: true,
${observability}		env: {
${env.join("\n")}
		},
		exports: {
${exportsLines.join("\n")}
		},
	},
});
`;
const alias = Object.entries(cfg.alias ?? {}).map(([k, v]) => `\t\t${q(k)}: ${q(v.startsWith(".") ? rel(v) : v)},`);
// Module rules (e.g. the console's qrcode-generator Text import) carry over as-is.
const rules = (cfg.rules ?? []).map(({ type, globs, fallthrough }) => `\t\t${q({ type, globs, ...(fallthrough === undefined ? {} : { fallthrough }) })},`);
const wranglerConfig = `// Generated by scripts/relay-dev/cf-config.mjs. Do not edit.
import { defineWranglerConfig } from "wrangler/experimental-config";

export default defineWranglerConfig({
	alias: {
${alias.join("\n")}
	},
	rules: [
${rules.join("\n")}
	],
	types: { generate: false },
});
`;
mkdirSync(dir, { recursive: true });
writeFileSync(resolve(dir, "cloudflare.config.ts"), cloudflareConfig);
writeFileSync(resolve(dir, "wrangler.config.ts"), wranglerConfig);
